### ISSUE TITLE
Cannot read property 'js' of undefined

### ISSUE THREAD

**Issue by ZerioDev** [yj01jung/nodetube#1]
Hello, i took the liberty of trying out your module which, despite a few changes, still doesn't work.

The code is as follows :

```js
async function create() {

    const { Youtube } = require('nodetube')

    const yt = new Youtube('mr_-enZXun0');

    const link = await yt.stream(37);

    console.log(link);
}

create();
```

The problem is this :

![image](https://user-images.githubusercontent.com/43386412/98440695-6ac2db80-20fa-11eb-9196-64806b539805.png)

Do you have a solution ? Have a nice day 😄

**Comment by yj01jung** [comment]
I am sorry that i cannot manage this repo.
But you can just node-ytdl-core
